//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComicsStores.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3506 Rindle Ct, Charlotte.
        /// </summary>
        public static string AddressF {
            get {
                return ResourceManager.GetString("AddressF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also arrange pickup..
        /// </summary>
        public static string Arrange {
            get {
                return ResourceManager.GetString("Arrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To arrange delivery, when placing an order, select the menu item Delivery by courier.
        /// </summary>
        public static string ArrangeDelivery {
            get {
                return ResourceManager.GetString("ArrangeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can come and buy comics in our online store that runs daily from 12:00 to 20:00.
        /// </summary>
        public static string BuyComicsOffline {
            get {
                return ResourceManager.GetString("BuyComicsOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        public static string ContactInf {
            get {
                return ResourceManager.GetString("ContactInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContInf {
            get {
                return ResourceManager.GetString("ContInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier delivery.
        /// </summary>
        public static string Couriedeliverys {
            get {
                return ResourceManager.GetString("Couriedeliverys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have courier delivery in Minsk..
        /// </summary>
        public static string CourierDelivery {
            get {
                return ResourceManager.GetString("CourierDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery and payment of comics.
        /// </summary>
        public static string DeliveryandPayment {
            get {
                return ResourceManager.GetString("DeliveryandPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our store wants to provide its customers with maximum comfort. We understand that sometimes it’s not very convenient to get to our stores if you live far away or have no free time. Therefore, we have provided the ability to deliver your favorite comics directly to your home..
        /// </summary>
        public static string DeliveryDescription {
            get {
                return ResourceManager.GetString("DeliveryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery is carried out the day after the order..
        /// </summary>
        public static string DeliveryNextDay {
            get {
                return ResourceManager.GetString("DeliveryNextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping cost 7$.
        /// </summary>
        public static string DeliveryPrice {
            get {
                return ResourceManager.GetString("DeliveryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery is carried out within a week from the date of placing the order.
        /// </summary>
        public static string DeliveryTime {
            get {
                return ResourceManager.GetString("DeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery to US.
        /// </summary>
        public static string DeliveryToBelarus {
            get {
                return ResourceManager.GetString("DeliveryToBelarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first fake comic book store in Minsk. We specialize in selling comics DC, Marvel, Vertigo, as well as Russian comics. We have delivery in Minsk and throughout Belarus. More detailed information can be found in the delivery and payment section. We only sell licensed and certified comics. We do not sell counterfeit products, comics with fan translation, etc..
        /// </summary>
        public static string DescriptonStore {
            get {
                return ResourceManager.GetString("DescriptonStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to buy comics if I live in Minsk.
        /// </summary>
        public static string HowBuyComics {
            get {
                return ResourceManager.GetString("HowBuyComics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manager will call you back after placing the order and specify the delivery time..
        /// </summary>
        public static string ManagerCall {
            get {
                return ResourceManager.GetString("ManagerCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our location.
        /// </summary>
        public static string Ourlocation {
            get {
                return ResourceManager.GetString("Ourlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is made in cash to the courier.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive a mail notification, after which you will need to contact your post office to make payment and pick up the order..
        /// </summary>
        public static string PostOfficeDelivery {
            get {
                return ResourceManager.GetString("PostOfficeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make delivery, when ordering, select the menu item Delivery by post office.
        /// </summary>
        public static string PostOfficeDeliveryType {
            get {
                return ResourceManager.GetString("PostOfficeDeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manager will call you back after placing an order to clarify the data..
        /// </summary>
        public static string PostOfficeManager {
            get {
                return ResourceManager.GetString("PostOfficeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishment.
        /// </summary>
        public static string Publishment {
            get {
                return ResourceManager.GetString("Publishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string Releasedate {
            get {
                return ResourceManager.GetString("Releasedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping and payment.
        /// </summary>
        public static string ShipAPay {
            get {
                return ResourceManager.GetString("ShipAPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by low price.
        /// </summary>
        public static string SorotbyL {
            get {
                return ResourceManager.GetString("SorotbyL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by height price.
        /// </summary>
        public static string SortbyH {
            get {
                return ResourceManager.GetString("SortbyH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comics Store.
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hours.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven days a week from 12:00 to 20:00.
        /// </summary>
        public static string WorkTimeF {
            get {
                return ResourceManager.GetString("WorkTimeF", resourceCulture);
            }
        }
    }
}
